version: '3.1'

services:

  db:
    image: mysql:5.7.21
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - /Users/goangle/labs/tdd-node-mysql/data:/var/lib/mysql    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080